version: 0.2
env:
  variables:
    EKS_CLUSTER_NAME: "retail-store-sample-2"
    EKS_KUBECTL_ROLE_ARN: "arn:aws:iam::347830095179:role/service-role/codebuild-retail-store-sample-app-service-role"
    RETAIL_APP_NS: "retail-store"
phases:
  build:
    commands:
      - echo "Update AWS CLI"
      #- pip3 uninstall -y awscli
      #- set -ex && yum install -y unzip
      #- curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - ls 
      #- unzip awscliv2.zip
      #- set -ex && ./aws/install --update
      #- export PATH=$PATH:/usr/local/bin
      - echo "aws cli version:"
      - aws --version
      - echo "Install Kubectl"
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - echo "ls\n" && ls -l
      - kubectl version --client
  post_build:
    commands:
      - echo "EKS_CLUSTER_NAME...  $EKS_CLUSTER_NAME"             
      # Setup kubectl with our EKS Cluster              
      - echo "Update Kube Config"      
      - aws eks update-kubeconfig --region eu-central-1 --name $EKS_CLUSTER_NAME
      - cat ~/.kubectl/config
      #- aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      # Apply changes to our Application using kubectl
      - echo "Rolling out update to cluster ${EKS_CLUSTER_NAME} into namespace ${RETAIL_APP_NS}"
      #- kubectl -ns "${RETAIL_APP_NS}" apply -f "dist/kubernetes/deploy.yaml"
      - kubectl --namespace "${RETAIL_APP_NS}" apply -f "dist/kubernetes/deploy.yaml"
      #- echo "Apply changes to kube manifests"            
      #- kubectl apply -f kube-manifests/
      - echo "Completed applying changes to Kubernetes Objects"           

      #- echo "Update Kube Config"      
      #- aws eks update-kubeconfig --name demo-eks-cluster
      #- echo "Apply changes to kube manifests"
      #- kubectl apply -f busybox-deployment.yaml
